apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuryrnetpolicies.openstack.org
spec:
  group: openstack.org
  version: v1
  scope: Namespaced
  names:
    plural: kuryrnetpolicies
    singular: kuryrnetpolicy
    kind: KuryrNetPolicy
    shortNames:
      - knp
